/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module button_control_4 (
    input clk,
    input btn,
    output reg out
  );
  
  
  
  localparam MANUAL_bc = 1'd0;
  localparam AUTO_bc = 1'd1;
  
  reg M_bc_d, M_bc_q = MANUAL_bc;
  
  always @* begin
    M_bc_d = M_bc_q;
    
    M_bc_d = M_bc_q;
    out = 1'h0;
    
    case (M_bc_q)
      AUTO_bc: begin
        if (btn == 1'h1) begin
          M_bc_d = MANUAL_bc;
        end
        out = 1'h1;
      end
      MANUAL_bc: begin
        if (btn == 1'h1) begin
          M_bc_d = AUTO_bc;
        end
        out = 1'h0;
      end
    endcase
  end
  
  always @(posedge clk) begin
    M_bc_q <= M_bc_d;
  end
  
endmodule
